### ISSUE TITLE
Not all annotations returned by API query

### ISSUE THREAD

**Issue by efeickmann** [ProteinsWebTeam/interpro7-api#128]
Hi,

I encountered an issue when querying the API for protein domain annotations. I used this URL to request annotations for protein Q92793: `https://www.ebi.ac.uk/interpro/api/entry/InterPro/protein/UniProt/Q92793`

The expected behavior was that the API would return information for all 27 annotations on this protein's [InterPro page](https://www.ebi.ac.uk/interpro/protein/reviewed/Q92793/entry/InterPro/#table). Accordingly, in the payload, `count` = 27. However, the payload only has information for 20 annotations, corresponding to the first page of annotations on the InterPro page.

Am I correct that this behavior is unexpected, or is there some way to specify the number of annotations to return using the request URL?

Thanks for your help!

**Comment by gustavo-salazar** [comment]
Hey there,
The default page size of our responses is `20`, that's why you only get that number on your requests.

You have 2 options:
1. Follow the navigation link `next` that is included in the response.
   ![Screenshot 2024-02-16 at 11 30 16](https://github.com/ProteinsWebTeam/interpro7-api/assets/46671268/42ebcfd7-315d-4fbd-b56c-41cf9bc2842b)
   [This page in the Interpro website](https://www.ebi.ac.uk/interpro/result/download/#/entry/InterPro/protein/UniProt/Q92793/|json)  can help you to generate scripts that are a good start to programmatically paginate over requests with lots of results.

2. Set a different `page_size`, for example: https://www.ebi.ac.uk/interpro/api/entry/InterPro/protein/UniProt/Q92793?page_size=100
  this however, is limited as the maximum `page_size` is set to `200`, so if you get a request with more than 200 results, then you need to paginate as in case 1.

**Comment by efeickmann** [comment]
Thank you for the clarification! I appreciate your help.
